services:
  - type: web
    name: my-portfolio
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: DB_HOST
        value: mysql-myportfolio56-sasi-14de.e.aivencloud.com
      - key: DB_PORT
        value: "21563"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        value: defaultdb
      - key: DB_SSL
        value: "true"
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_SECURE
        value: ssl
      - key: SMTP_USER
        value: venugopalmugada@gmail.com
      - key: SMTP_PASS
        sync: false
      - key: OWNER_EMAIL
        value: priyamugada9@gmail.com
      - key: OWNER_NAME
        value: priya mugada
